### ISSUE TITLE
License request for the promise rejection polyfill

### ISSUE THREAD

**Issue by ilbmiller** [rconnamacher/practiceexam#1]
Hi Richard,
    Sorry to contact you this way, but I can't find any contact info to contact you directly.  

   I took a look at your promise rejection polyfill gist (https://gist.github.com/rconnamacher/08c010eae3da8233d35500c9bbc8ba54), and it is a nice piece of code!  We'd potentially like to use it, but we'd need to know the License for it - can you clarify what the license would be?

Thanks,
Brad

**Comment by rconnamacher** [comment]
Thanks! I updated it with a license clause (Simplified BSD).
